name: Add domain from issue

on:
  issues:
    types: [opened]

permissions:
  contents: write
  issues: write

jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract and normalize domain
        id: parse
        run: |
          RAW_TITLE="${{ github.event.issue.title }}"
          DOMAIN=$(echo "$RAW_TITLE" | sed -E 's/Добавить[:：]?[[:space:]]*//' | sed -E 's/^www\.//' | tr -d '[:space:]' | tr -cd 'a-zA-Z0-9.-')
          echo "DOMAIN=$DOMAIN" >> $GITHUB_ENV

      - name: Check if domain already exists
        id: check
        run: |
          if grep -q "+.$DOMAIN" my-local-rules.yaml; then
            echo "EXISTS=true" >> $GITHUB_ENV
          else
            echo
