name: Build IPv4 MRS

on:
  schedule:
    - cron: "0 3 * * *"   # запуск каждый день в 03:00 по UTC
  workflow_dispatch:       # возможность запускать вручную

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install mihomo-rule-converter
        run: |
          go install github.com/MetaCubeX/mihomo-rule-converter@latest

      - name: Download IPv4 lists
        run: |
          mkdir ipv4
          wget -q -O ipv4/cloudflare.lst      https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Subnets/IPv4/cloudflare.lst
          wget -q -O ipv4/cloudfront.lst      https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Subnets/IPv4/cloudfront.lst
          wget -q -O ipv4/digitalocean.lst    https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Subnets/IPv4/digitalocean.lst
          wget -q -O ipv4/discord.lst         https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Subnets/IPv4/discord.lst
          wget -q -O ipv4/google_meet.lst     https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Subnets/IPv4/google_meet.lst
          wget -q -O ipv4/hetzner.lst         https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Subnets/IPv4/hetzner.lst
          wget -q -O ipv4/meta.lst            https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Subnets/IPv4/meta.lst
          wget -q -O ipv4/ovh.lst             https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Subnets/IPv4/ovh.lst
          wget -q -O ipv4/roblox.lst          https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Subnets/IPv4/roblox.lst
          wget -q -O ipv4/telegram.lst        https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Subnets/IPv4/telegram.lst
          wget -q -O ipv4/twitter.lst         https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Subnets/IPv4/twitter.lst

      - name: Merge all lists into one
        run: |
          cat ipv4/*.lst | sort -u > all-ipv4.lst

      - name: Convert to MRS
        run: |
          echo "payload:" > all-ipv4.yaml
          sed 's/^/  - IP-CIDR,/' all-ipv4.lst >> all-ipv4.yaml
          ~/go/bin/mihomo-rule-converter -i all-ipv4.yaml -o all-ipv4.mrs

      - name: Commit and push
        run: |
          mkdir -p ipv4-mrs
          mv all-ipv4.mrs ipv4-mrs/all-ipv4.mrs
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add ipv4-mrs/all-ipv4.mrs
          git commit -m "Auto-update all-ipv4.mrs" || echo "No changes"
          git push
